In [1]:
import os 
os.listdir("../data/raw")

['US_Accidents_March23.csv']

In [2]:
import pandas as pd 

df = pd.read_csv("../data/raw/US_Accidents_March23.csv")
df.head()

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,Source2,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,Source2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,0.01,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,0.01,...,False,False,False,False,True,False,Day,Day,Day,Day

In [3]:
df.shape

(7728394, 46)

In [4]:
df.columns

Index(['ID', 'Source', 'Severity', 'Start_Time', 'End_Time', 'Start_Lat',
       'Start_Lng', 'End_Lat', 'End_Lng', 'Distance(mi)', 'Description',
       'Street', 'City', 'County', 'State', 'Zipcode', 'Country', 'Timezone',
       'Airport_Code', 'Weather_Timestamp', 'Temperature(F)', 'Wind_Chill(F)',
       'Humidity(%)', 'Pressure(in)', 'Visibility(mi)', 'Wind_Direction',
       'Wind_Speed(mph)', 'Precipitation(in)', 'Weather_Condition', 'Amenity',
       'Bump', 'Crossing', 'Give_Way', 'Junction', 'No_Exit', 'Railway',
       'Roundabout', 'Station', 'Stop', 'Traffic_Calming', 'Traffic_Signal',
       'Turning_Loop', 'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight',
       'Astronomical_Twilight'],
      dtype='object')

In [5]:
selected_cols=[
    "Start_Time",
    "Start_Lat",
    "Start_Lng",
    "Severity",
    "Weather_Condition",
    "Visibility(mi)",
    "Wind_Speed(mph)",
    "Temperature(F)",
    "Precipitation(in)"
]

df = df[selected_cols]
df.head()

,Start_Time,Start_Lat,Start_Lng,Severity,Weather_Condition,Visibility(mi),Wind_Speed(mph),Temperature(F),Precipitation(in)
0,2016-02-08 05:46:00,39.865147,-84.058723,3,Light Rain,10.0,NaN,36.9,0.02
1,2016-02-08 06:07:59,39.928059,-82.831184,2,Light Rain,10.0,NaN,37.9,0.00
2,2016-02-08 06:49:27,39.063148,-84.032608,2,Overcast,10.0,3.5,36.0,NaN
3,2016-02-08 07:23:34,39.747753,-84.205582,3,Mostly Cloudy,9.0,4.6,35.1,NaN
4,2016-02-08 07:39:07,39.627781,-84.188354,2,Mostly Cloudy,6.0,3.5,36.0,NaN

In [6]:
df.isnull().sum()

Start_Time                 0
Start_Lat                  0
Start_Lng                  0
Severity                   0
Weather_Condition     173459
Visibility(mi)        177098
Wind_Speed(mph)       571233
Temperature(F)        163853
Precipitation(in)    2203586
dtype: int64

In [7]:
num_cols = [
     "Visibility(mi)",
    "Wind_Speed(mph)",
    "Temperature(F)",
    "Precipitation(in)"
]

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

In [8]:
df["Weather_Condition"] = df["Weather_Condition"].fillna("Unknown")

In [9]:
df["Weather_Condition"] = df["Weather_Condition"].astype("category").cat.codes

In [10]:
df.isnull().sum()

Start_Time           0
Start_Lat            0
Start_Lng            0
Severity             0
Weather_Condition    0
Visibility(mi)       0
Wind_Speed(mph)      0
Temperature(F)       0
Precipitation(in)    0
dtype: int64

In [11]:
df['Severity'].value_counts()

Severity
2    6156981
3    1299337
4     204710
1      67366
Name: count, dtype: int64

In [12]:
df.describe()

,Start_Lat,Start_Lng,Severity,Weather_Condition,Visibility(mi),Wind_Speed(mph),Temperature(F),Precipitation(in)
count,7.728394e+06,7.728394e+06,7.728394e+06,7.728394e+06,7.728394e+06,7.728394e+06,7.728394e+06,7.728394e+06
mean,3.620119e+01,-9.470255e+01,2.212384e+00,4.491441e+01,9.111221e+00,7.634823e+00,6.171283e+01,6.010074e-03
std,5.076079e+00,1.739176e+01,4.875313e-01,3.945819e+01,2.660819e+00,5.223725e+00,1.881403e+01,9.327228e-02
min,2.455480e+01,-1.246238e+02,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-8.900000e+01,0.000000e+00
25%,3.339963e+01,-1.172194e+02,2.000000e+00,1.600000e+01,1.000000e+01,5.000000e+00,5.000000e+01,0.000000e+00
50%,3.582397e+01,-8.776662e+01,2.000000e+00,1.600000e+01,1.000000e+01,7.000000e+00,6.400000e+01,0.000000e+00
75%,4.008496e+01,-8.035368e+01,2.000000e+00,8.500000e+01,1.000000e+01,1.000000e+01,7.600000e+01,0.000000e+00
max,4.900220e+01,-6.711317e+01,4.000000e+00,1.440000e+02,1.400000e+02,1.087000e+03,2.070000e+02,3.647000e+01

In [13]:
# Convert Start_time to datetime--->>>>
df["Start_Time"] = pd.to_datetime(df["Start_Time"], errors="coerce")

In [14]:
# Extract time-Based Features---->>>

df["hour"] = df["Start_Time"].dt.hour
df["day"] = df["Start_Time"].dt.day
df["month"] = df["Start_Time"].dt.month
df["weekday"] = df["Start_Time"].dt.weekday

In [15]:
df["is_weekend"] = df["weekday"].isin([5,6]).astype(int)
df["is_night"] = df["hour"].apply(lambda x: 1 if (x >= 19 or x <= 6) else 0)

In [16]:
# Create a location_based risk feature---->>>
df['lat_bin'] = df['Start_Lat'].round(2)
df['lng_bin'] = df['Start_Lng'].round(2)

In [17]:
# Create Historical Accidents

location_risk = (
    df.groupby(['lat_bin','lng_bin'])
                .size()
                .reset_index(name="accident_count")
)

df = df.merge(location_risk, on=['lat_bin','lng_bin'],how='left')

In [18]:
# Select features for Modeling(Independent or Dependent Features)--->>>>>

feature_cols = [
    "hour",
    "is_night",
    "is_weekend",
    "lat_bin",
    "lng_bin",
    "Weather_Condition",
    "Visibility(mi)",
    "Wind_Speed(mph)",
    "Temperature(F)",
    "Precipitation(in)",
    "accident_count"
]

X = df[feature_cols]
y = df['Severity']

In [19]:
# Sort Data by time 
df = df.sort_values("Start_Time").reset_index(drop=True)

In [20]:
# Keep only 300k rows (you can try 200k if needed as data is 6 gib) --->>>>>
df_small = df.iloc[:300_000].copy()

In [21]:
X_small = df_small[feature_cols]
y_small = df_small["Severity"]

In [22]:
# Scale Features

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_scaled = scaler.fit_transform(X_small)

In [23]:
# Define Sequence Length (Predict risk on base of past Data)---->>>>

SEQ_LEN = 10 # YOU CAN LATER TRY 20,30

In [24]:
# Create Sequences--->>>

import numpy as np

def create_sequence(X_small,y_small,seq_len):
    X_seq = []
    y_seq = []

    for i in range(len(X_small) - seq_len):
         X_seq.append(X_small[i:i+seq_len])
         y_seq.append(y_small.iloc[i+seq_len])

    return np.array(X_seq), np.array(y_seq)

In [25]:
X_seq,y_seq = create_sequence(X_scaled,y_small,SEQ_LEN)

print(X_seq.shape)
print(y_seq.shape)

(299990, 10, 11)
(299990,)

In [26]:
# Train-test Split--->>>

split_idx = int(0.8*len(X_seq))

X_train,X_test = X_seq[:split_idx], X_seq[split_idx:]
y_train,y_test = y_seq[:split_idx], y_seq[split_idx:]

In [27]:
# Importing Deep Learning Libraries---->>>
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

C:\Users\ASUS\anaconda3\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):

In [29]:
# Build the LSTM architecture ----->>>>>

model = Sequential([
    LSTM(64, return_sequences=True, input_shape=(X_train.shape[1], X_train.shape[2])),
    Dropout(0.3),

    LSTM(32),
    Dropout(0.3),

    Dense(1, activation="linear") # Predicting serverity (1-4)
    
])

model.compile(
    optimizer="adam",
    loss="mse",
    metrics=["mae"]
)

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ lstm_1 (LSTM)                        │ (None, 10, 64)              │          19,456 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 10, 64)              │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_2 (LSTM)                        │ (None, 32)                  │          12,416 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 32)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 31,905 (124.63 KB)

 Trainable params: 31,905 (124.63 KB)

 Non-trainable params: 0 (0.00 B)

In [30]:
# Train/test split 
early_stop = EarlyStopping(
    monitor = "val_loss",
    patience=3,
    restore_best_weights=True
)

In [32]:
history = model.fit(
    X_train, y_train,
    validation_data=(X_test,y_test),
    epochs=10,
    batch_size=128,
    callbacks=[early_stop],
    verbose=1
)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 68s 31ms/step - loss: 0.3914 - mae: 0.5076 - val_loss: 0.2901 - val_mae: 0.4768
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 85s 33ms/step - loss: 0.3435 - mae: 0.4884 - val_loss: 0.2926 - val_mae: 0.4901
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 78s 31ms/step - loss: 0.3217 - mae: 0.4839 - val_loss: 0.2902 - val_mae: 0.4867
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 103s 33ms/step - loss: 0.3093 - mae: 0.4838 - val_loss: 0.2904 - val_mae: 0.4652

In [33]:
loss, mae = model.evaluate(X_test, y_test, verbose=0)
print(f"Test MAE: {mae:.3f}")

Test MAE: 0.477

In [38]:
from tensorflow.keras.models import load_model
model = load_model("../models/saved_model/accident_lstm.h5", compile=False)

In [39]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ lstm_1 (LSTM)                        │ (None, 10, 64)              │          19,456 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 10, 64)              │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_2 (LSTM)                        │ (None, 32)                  │          12,416 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 32)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 31,905 (124.63 KB)

 Trainable params: 31,905 (124.63 KB)

 Non-trainable params: 0 (0.00 B)